if (CMAKE_VERSION VERSION_LESS 3.19)
    message(FATAL_ERROR "QQNTSdk: CMake >= 3.19 required (string(JSON), file(ARCHIVE_EXTRACT)).")
endif ()

if (NOT DEFINED QQNT_SDK_VERSION)
    set(QQNT_SDK_VERSION "latest")
endif ()
if (NOT DEFINED QQNT_SDK_LINK_LIBS)
    set(QQNT_SDK_LINK_LIBS ON)
endif ()
if (NOT DEFINED QQNT_SDK_OFFLINE)
    set(QQNT_SDK_OFFLINE OFF)
endif ()
if (NOT DEFINED QQNT_SDK_UPDATE)
    set(QQNT_SDK_UPDATE OFF)
endif ()

if (WIN32)
    set(_qq_sys "windows")
elseif (UNIX AND NOT APPLE)
    set(_qq_sys "linux")
else ()
    message(FATAL_ERROR "QQNTSdk: only windows/linux SDK packages are published.")
endif ()

if (NOT QQNT_SDK_ARCH)
    if (CMAKE_SYSTEM_PROCESSOR MATCHES "[Aa][Rr][Mm]64|aarch64")
        set(QQNT_SDK_ARCH "arm64")
    elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64|amd64|x64")
        set(QQNT_SDK_ARCH "x64")
    elseif (CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(QQNT_SDK_ARCH "x64")
    else ()
        message(FATAL_ERROR "QQNTSdk: cannot infer arch from '${CMAKE_SYSTEM_PROCESSOR}'; set QQNT_SDK_ARCH.")
    endif ()
endif ()
set(_qq_slot "${_qq_sys}-${QQNT_SDK_ARCH}")

if (NOT QQNT_SDK_REPO)
    find_program(_qq_git git)
    if (_qq_git)
        execute_process(COMMAND ${_qq_git} -C "${CMAKE_CURRENT_LIST_DIR}" remote get-url origin
                OUTPUT_VARIABLE _qq_origin OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        if (_qq_origin MATCHES "github\\.com[:/]+([^/]+/[^/]+)")
            string(REGEX REPLACE "\\.git$" "" QQNT_SDK_REPO "${CMAKE_MATCH_1}")
        endif ()
    endif ()
endif ()
if (NOT QQNT_SDK_REPO)
    set(QQNT_SDK_REPO "CloverNT/qqnt-sdk")   # default: this project's repo
endif ()

if (NOT QQNT_SDK_CACHE_DIR)
    if (DEFINED ENV{QQNT_SDK_CACHE_DIR})
        set(QQNT_SDK_CACHE_DIR "$ENV{QQNT_SDK_CACHE_DIR}")
    elseif (WIN32 AND DEFINED ENV{LOCALAPPDATA})
        set(QQNT_SDK_CACHE_DIR "$ENV{LOCALAPPDATA}/qqnt-sdk")
    elseif (DEFINED ENV{XDG_CACHE_HOME})
        set(QQNT_SDK_CACHE_DIR "$ENV{XDG_CACHE_HOME}/qqnt-sdk")
    elseif (DEFINED ENV{HOME})
        set(QQNT_SDK_CACHE_DIR "$ENV{HOME}/.cache/qqnt-sdk")
    else ()
        set(QQNT_SDK_CACHE_DIR "${CMAKE_BINARY_DIR}/qqnt-sdk")
    endif ()
endif ()
file(MAKE_DIRECTORY "${QQNT_SDK_CACHE_DIR}")

set(_qq_hdr "Accept: application/vnd.github+json")
if (QQNT_SDK_GITHUB_TOKEN)
    set(_qq_auth "Authorization: Bearer ${QQNT_SDK_GITHUB_TOKEN}")
else ()
    set(_qq_auth "X-QQNT-NoAuth: 1")   # harmless placeholder header
endif ()

function(_qq_find_cached out_dir)
    set(${out_dir} "" PARENT_SCOPE)
    file(GLOB _cands "${QQNT_SDK_CACHE_DIR}/qqnt-sdk-*-${_qq_slot}")
    list(SORT _cands)
    list(REVERSE _cands)   # newest version sorts last -> first after reverse
    foreach (_c ${_cands})
        if (IS_DIRECTORY "${_c}" AND EXISTS "${_c}/.qqnt-sdk-ok")
            set(${out_dir} "${_c}" PARENT_SCOPE)
            return()
        endif ()
    endforeach ()
endfunction()

function(_qq_gyvar txt name out)
    set(${out} 0 PARENT_SCOPE)
    if (txt MATCHES "'${name}' *: *([0-9]+)")
        set(${out} "${CMAKE_MATCH_1}" PARENT_SCOPE)
    endif ()
endfunction()

set(_qq_req "${QQNT_SDK_VERSION}:${_qq_slot}")
set(_qq_dir "")
if (NOT QQNT_SDK_UPDATE
        AND DEFINED QQNT_SDK_CACHED_DIR
        AND QQNT_SDK_CACHED_REQ STREQUAL "${_qq_req}"
        AND EXISTS "${QQNT_SDK_CACHED_DIR}/.qqnt-sdk-ok")
    set(_qq_dir "${QQNT_SDK_CACHED_DIR}")
    message(STATUS "QQNTSdk: using cached SDK ${_qq_dir}")
endif ()

if (NOT _qq_dir)
    if (QQNT_SDK_OFFLINE)
        _qq_find_cached(_qq_dir)
        if (NOT _qq_dir)
            message(FATAL_ERROR "QQNTSdk: OFFLINE and no cached ${_qq_slot} SDK in ${QQNT_SDK_CACHE_DIR}.")
        endif ()
        message(STATUS "QQNTSdk: OFFLINE, using cached ${_qq_dir}")
    else ()
        if (QQNT_SDK_VERSION STREQUAL "latest")
            set(_qq_api "https://api.github.com/repos/${QQNT_SDK_REPO}/releases/latest")
        else ()
            if (QQNT_SDK_VERSION MATCHES "^qq-")
                set(_qq_tag "${QQNT_SDK_VERSION}")
            else ()
                set(_qq_tag "qq-${QQNT_SDK_VERSION}")
            endif ()
            set(_qq_api "https://api.github.com/repos/${QQNT_SDK_REPO}/releases/tags/${_qq_tag}")
        endif ()

        set(_qq_json "${QQNT_SDK_CACHE_DIR}/.release-${QQNT_SDK_VERSION}-${_qq_slot}.json")
        message(STATUS "QQNTSdk: querying ${_qq_api}")
        file(DOWNLOAD "${_qq_api}" "${_qq_json}"
                HTTPHEADER "${_qq_hdr}" HTTPHEADER "${_qq_auth}" TLS_VERIFY ON STATUS _qq_st)
        list(GET _qq_st 0 _qq_rc)
        if (NOT _qq_rc EQUAL 0)
            list(GET _qq_st 1 _qq_msg)
            message(FATAL_ERROR "QQNTSdk: release query failed (${_qq_msg}). URL: ${_qq_api}")
        endif ()

        file(READ "${_qq_json}" _qq_body)
        string(JSON _qq_n ERROR_VARIABLE _qq_jerr LENGTH "${_qq_body}" assets)
        if (_qq_jerr OR NOT _qq_n)
            message(FATAL_ERROR "QQNTSdk: no assets in release JSON (${_qq_jerr}).")
        endif ()
        set(_qq_name "")
        set(_qq_url "")
        math(EXPR _qq_last "${_qq_n} - 1")
        foreach (_i RANGE 0 ${_qq_last})
            string(JSON _qq_a GET "${_qq_body}" assets ${_i})
            string(JSON _qq_an GET "${_qq_a}" name)
            if (_qq_an MATCHES "^qqnt-sdk-.*-${_qq_slot}\\.zip$")
                string(JSON _qq_url GET "${_qq_a}" browser_download_url)
                set(_qq_name "${_qq_an}")
                break()
            endif ()
        endforeach ()
        if (NOT _qq_name)
            message(FATAL_ERROR "QQNTSdk: no qqnt-sdk-*-${_qq_slot}.zip asset in ${_qq_api}.")
        endif ()

        string(REGEX REPLACE "\\.zip$" "" _qq_stem "${_qq_name}")
        set(_qq_dir "${QQNT_SDK_CACHE_DIR}/${_qq_stem}")
        set(_qq_zip "${QQNT_SDK_CACHE_DIR}/${_qq_name}")

        if (EXISTS "${_qq_dir}/.qqnt-sdk-ok")
            message(STATUS "QQNTSdk: already cached ${_qq_stem}")
        else ()
            if (NOT EXISTS "${_qq_zip}")
                message(STATUS "QQNTSdk: downloading ${_qq_name}")
                file(DOWNLOAD "${_qq_url}" "${_qq_zip}.part"
                        HTTPHEADER "${_qq_auth}" TLS_VERIFY ON SHOW_PROGRESS STATUS _qq_dst)
                list(GET _qq_dst 0 _qq_drc)
                if (NOT _qq_drc EQUAL 0)
                    file(REMOVE "${_qq_zip}.part")
                    list(GET _qq_dst 1 _qq_dmsg)
                    message(FATAL_ERROR "QQNTSdk: download failed (${_qq_dmsg}). URL: ${_qq_url}")
                endif ()
                file(RENAME "${_qq_zip}.part" "${_qq_zip}")
            endif ()
            message(STATUS "QQNTSdk: extracting ${_qq_name}")
            file(REMOVE_RECURSE "${_qq_dir}")
            file(ARCHIVE_EXTRACT INPUT "${_qq_zip}" DESTINATION "${QQNT_SDK_CACHE_DIR}")
            if (NOT IS_DIRECTORY "${_qq_dir}/include/QQNT")
                message(FATAL_ERROR "QQNTSdk: extracted SDK missing include/QQNT (${_qq_dir}).")
            endif ()
            file(WRITE "${_qq_dir}/.qqnt-sdk-ok" "${_qq_name}\n")
        endif ()
    endif ()

    set(QQNT_SDK_CACHED_DIR "${_qq_dir}" CACHE INTERNAL "resolved QQNT SDK dir")
    set(QQNT_SDK_CACHED_REQ "${_qq_req}" CACHE INTERNAL "resolved QQNT SDK request key")
endif ()

set(QQNT_SDK_VERSION_RESOLVED "")
set(QQNT_NODE_VERSION "")
set(QQNT_ELECTRON_VERSION "")
set(QQNT_V8_VERSION "")
if (EXISTS "${_qq_dir}/manifest.txt")
    file(STRINGS "${_qq_dir}/manifest.txt" _qq_man)
    foreach (_l ${_qq_man})
        if (_l MATCHES "^version=(.+)$")
            set(QQNT_SDK_VERSION_RESOLVED "${CMAKE_MATCH_1}")
        elseif (_l MATCHES "^node=(.+)$")
            set(QQNT_NODE_VERSION "${CMAKE_MATCH_1}")
        elseif (_l MATCHES "^electron=(.+)$")
            set(QQNT_ELECTRON_VERSION "${CMAKE_MATCH_1}")
        elseif (_l MATCHES "^v8=(.+)$")
            set(QQNT_V8_VERSION "${CMAKE_MATCH_1}")
        elseif (_l MATCHES "^v8_defines=(.+)$")
            string(REPLACE "," ";" _qq_v8defs_manifest "${CMAKE_MATCH_1}")
        endif ()
    endforeach ()
endif ()

set(QQNT_SDK_DIR "${_qq_dir}")
set(QQNT_SDK_INCLUDE_DIR "${_qq_dir}/include")
set(QQNT_SDK_LIB_DIR "${_qq_dir}/lib")

set(_qq_libs "")
if (QQNT_SDK_LINK_LIBS)
    if (_qq_sys STREQUAL "windows")
        file(GLOB _qq_libs "${_qq_dir}/lib/*.lib")
    else ()
        file(GLOB _qq_libs "${_qq_dir}/lib/*.node" "${_qq_dir}/lib/*.so")
    endif ()
endif ()

set(QQNT_V8_DEFINES "")
set(_qq_gypi "${_qq_dir}/include/QQNT/config.gypi")
if (EXISTS "${_qq_gypi}")
    file(READ "${_qq_gypi}" _qq_gypi_txt)
    _qq_gyvar("${_qq_gypi_txt}" "v8_enable_pointer_compression" _qq_pc)
    _qq_gyvar("${_qq_gypi_txt}" "v8_enable_pointer_compression_shared_cage" _qq_sc)
    _qq_gyvar("${_qq_gypi_txt}" "v8_enable_31bit_smis_on_64bit_arch" _qq_smis)
    _qq_gyvar("${_qq_gypi_txt}" "v8_enable_sandbox" _qq_sbx)
    _qq_gyvar("${_qq_gypi_txt}" "v8_enable_zone_compression" _qq_zone)
    _qq_gyvar("${_qq_gypi_txt}" "v8_enable_conservative_stack_scanning" _qq_css)
    _qq_gyvar("${_qq_gypi_txt}" "v8_enable_direct_local" _qq_dl)
    _qq_gyvar("${_qq_gypi_txt}" "v8_enable_map_packing" _qq_mp)
    if (_qq_pc EQUAL 1)
        list(APPEND QQNT_V8_DEFINES V8_COMPRESS_POINTERS)
    endif ()
    if (_qq_sc EQUAL 1)
        list(APPEND QQNT_V8_DEFINES V8_COMPRESS_POINTERS_IN_SHARED_CAGE)
    endif ()
    if (_qq_pc EQUAL 1 AND NOT _qq_sc EQUAL 1)
        list(APPEND QQNT_V8_DEFINES V8_COMPRESS_POINTERS_IN_ISOLATE_CAGE)
    endif ()
    if (_qq_pc EQUAL 1 OR _qq_smis EQUAL 1)
        list(APPEND QQNT_V8_DEFINES V8_31BIT_SMIS_ON_64BIT_ARCH)
    endif ()
    if (_qq_zone EQUAL 1)
        list(APPEND QQNT_V8_DEFINES V8_COMPRESS_ZONES)
    endif ()
    if (_qq_sbx EQUAL 1)
        list(APPEND QQNT_V8_DEFINES V8_ENABLE_SANDBOX)
    endif ()
    if (_qq_css EQUAL 1)
        list(APPEND QQNT_V8_DEFINES V8_ENABLE_CONSERVATIVE_STACK_SCANNING)
    endif ()
    if (_qq_dl EQUAL 1)
        list(APPEND QQNT_V8_DEFINES V8_ENABLE_DIRECT_LOCAL)
    endif ()
    if (_qq_mp EQUAL 1)
        list(APPEND QQNT_V8_DEFINES V8_MAP_PACKING)
    endif ()
elseif (DEFINED _qq_v8defs_manifest)
    set(QQNT_V8_DEFINES "${_qq_v8defs_manifest}")   # fallback: package lacks config.gypi
endif ()

set(_qq_alldefs "${QQNT_V8_DEFINES}")
list(APPEND _qq_alldefs BUILDING_NODE_EXTENSION USING_V8_SHARED=1 USING_UV_SHARED=1)

set(_qq_inc_dirs "${QQNT_SDK_INCLUDE_DIR}")
if (IS_DIRECTORY "${QQNT_SDK_INCLUDE_DIR}/QQNT")
    list(APPEND _qq_inc_dirs "${QQNT_SDK_INCLUDE_DIR}/QQNT")
endif ()
if (NOT TARGET QQNT::QQNT)
    add_library(QQNT::QQNT INTERFACE IMPORTED)
endif ()
set_property(TARGET QQNT::QQNT PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${_qq_inc_dirs}")
if (_qq_libs)
    set_property(TARGET QQNT::QQNT PROPERTY INTERFACE_LINK_LIBRARIES "${_qq_libs}")
endif ()
set_property(TARGET QQNT::QQNT PROPERTY INTERFACE_COMPILE_DEFINITIONS "${_qq_alldefs}")

